ViewCreator3d default lighting update
iTwin/itwinjs-core pull request #2681
Opened 2021-11-10 14:44 UTC by Ellord207

This change updates the default view created by the ViewCreator3d with brighter lighting.  A flag was also added to the ViewCreatorOptions that would allow users to op-out of the display styling changes.

2021-11-10 14:53 UTC, pmconne requested changes
Are you intentionally not enabling ambient occlusion?

I would like to see a test that confirms the new option behaves as intended when true, false, and undefined.

2021-11-10 14:53 UTC, pmconne commented on core/frontend/src/ViewCreator3d.ts
> +  useV2Stylings?: boolean;
I think this should be called `useDefaultLighting` and documentation should clarify what it does if true vs what it does if false/undefined.

2021-11-10 14:53 UTC, pmconne commented on common/api/summary/core-common.exports.csv
> +beta;DefaultSupportedTypes
This file shouldn't have been modified.

2021-11-11 20:41 UTC, Ellord207 commented
Due to authentication issues.  I'm going to delete this branch and recreated it.  I'll try and move the comments over to the new PR assuming it doesn't re-open this one.

2021-11-11 20:41 UTC, closed without merging