Presentation: Improve performance of getElementProperties API
iTwin/itwinjs-core pull request #2754
Opened 2021-11-19 16:59 UTC by saskliutas

Reduced number of queries that are run when getting properties for all elements.

2021-11-21 11:05 UTC, grigasp requested changes

2021-11-21 15:45 UTC, roluk commented on presentation/backend/src/presentation-backend/PresentationManager.ts
> +  public async getElementProperties(requestOptions: Prioritized<MultiElementPropertiesRequestOptions<IModelDb>>): Promise<AsyncIterableIterator<PagedResponse<ElementProperties>>>;
I do not agree because this is an async iterator. Serving items in pages allow consumers to process a batch of items synchronously.

2021-11-22 15:09 UTC, saskliutas commented on presentation/backend/src/presentation-backend/PresentationManager.ts
> +  private _onMangerUsed?: () => void;
Fixed, thanks

2021-11-22 15:09 UTC, saskliutas commented on presentation/backend/src/presentation-backend/TemporaryStorage.ts
> +    const tempValue = { value, lastUsed: new Date() };
Changed

2021-11-22 15:10 UTC, saskliutas commented on presentation/backend/src/presentation-backend/TemporaryStorage.ts
> +    this.props.onCreated && this.props.onCreated(id, value, /* istanbul ignore next */() => tempValue.lastUsed = new Date());
Added test for this

2021-11-22 16:20 UTC, grigasp approved these changes

2021-11-23 08:29 UTC, saskliutas commented
@Mergifyio update

2021-11-23 10:56 UTC, merged