Add support for hosting an imodel view in a modeless dialog
iTwin/itwinjs-core pull request #3068
Opened 2022-01-19 20:43 UTC by bsteinbk

Added ContentDialogManager, ContentDialog, and FloatingViewportContentControl to allow imodel viewport in a modeless dialog.

2022-01-19 20:45 UTC, pmconne requested changes
This sounds like a very useful feature (wasn't it requested by a user?) Please include some info + doc links in NextVersion.md.

2022-01-19 20:56 UTC, NancyMcCallB commented on ui/appui-react/src/appui-react/configurableui/ConfigurableUiManager.ts
> +    // Initialize dialog managers that require a
That require a what?

2022-01-20 19:21 UTC, bsteinbk commented on ui/appui-react/src/appui-react/configurableui/ConfigurableUiManager.ts
> +    // Initialize dialog managers that require a
updated

2022-01-20 21:43 UTC, NancyMcCallB approved these changes

2022-01-20 21:57 UTC, bsteinbk commented
@pmconne - added learning doc and nextversion entry.

2022-01-21 12:05 UTC, pmconne commented on docs/learning/ui/appui-react/ContentViews.md
> +![Floating iModel Content Dialog](./images/ModalDialog.png "Floating iModel Content Dialog")
Path to image is incorrect. Please also include image in NextVersion.md.

2022-01-21 14:27 UTC, mdastous-bentley approved these changes

2022-01-21 16:39 UTC, merged