Deprecate IModelReadRpcInterface.getViewThumbnail
iTwin/itwinjs-core pull request #3138
Opened 2022-01-31 15:33 UTC by swbsi

Fixes 431607 in TFS.

2022-01-31 15:37 UTC, pmconne requested changes
Please deprecate the `@public` `IModelConnection.Views.getThumbnail` function that calls this `@internal` RPC function, indicating that it will always throw.

2022-01-31 15:48 UTC, swbsi commented
> Please deprecate the `@public` `IModelConnection.Views.getThumbnail` function that calls this `@internal` RPC function, indicating that it will always throw.

Will do.

2022-01-31 18:59 UTC, pmconne approved these changes

2022-01-31 19:09 UTC, bbastings approved these changes

2022-01-31 19:30 UTC, bsteinbk approved these changes

2022-02-02 17:48 UTC, calebmshafer commented
@Mergifyio update

2022-02-02 17:49 UTC, calebmshafer approved these changes

2022-02-02 22:08 UTC, merged