Presentation: Final docs review
iTwin/itwinjs-core pull request #3388
Opened 2022-03-21 09:38 UTC by grigasp

TODO:
- [x] Cross-link rule and specification markdowns
- [ ] Add attribute information tables
- [ ] Cross-link markdowns and TS docs
- [ ] Remove `.snag` files

2022-03-24 10:10 UTC, grigasp commented
@iTwin/itwinjs-core-presentation, this is ready for review.

One thing I I'm not sure about is whether we need to link each attribute to its markdown docs. At the moment I only link interfaces. Would be happy to hear your thoughts on this.

2022-03-24 17:13 UTC, roluk requested changes

2022-03-24 17:13 UTC, roluk commented on presentation/common/src/presentation-common/rules/customization/SortingRule.ts
> + *R ule to disable sorting for certain ECInstances in the hierarchy and/or content.
```suggestion
 * Rule to disable sorting for certain ECInstances in the hierarchy and/or content.
```

2022-03-25 06:50 UTC, grigasp commented on docs/presentation/hierarchies/CustomNode.md
> +| **Performance note** | Setting the attribute to `Always` or `Never` may substantially improve performance of creating nodes in cases when  getting child nodes is expensive |
Made some changes, please check https://github.com/iTwin/itwinjs-core/pull/3388/commits/4f258d42bc5560b047bdad458ac08c4f104f6d8a

2022-03-25 06:50 UTC, grigasp commented on docs/presentation/hierarchies/InstanceNodesOfSpecificClasses.md
> +| **Performance note** | Setting the attribute to `true` may substantially improve performance when creating large numbers of nodes |
Made some changes, please check https://github.com/iTwin/itwinjs-core/pull/3388/commits/4f258d42bc5560b047bdad458ac08c4f104f6d8a

2022-03-25 06:50 UTC, grigasp commented on docs/presentation/hierarchies/InstanceNodesOfSpecificClasses.md
> +| **Performance note** | Setting the attribute to `Always` or `Never` may substantially improve performance of creating nodes in cases when  getting child nodes is expensive |
Made some changes, please check https://github.com/iTwin/itwinjs-core/pull/3388/commits/4f258d42bc5560b047bdad458ac08c4f104f6d8a

2022-03-25 06:50 UTC, grigasp commented on docs/presentation/hierarchies/RelatedInstanceNodes.md
> +| **Performance note** | Setting the attribute to `true` may substantially improve performance when creating large numbers of nodes |
Made some changes, please check https://github.com/iTwin/itwinjs-core/pull/3388/commits/4f258d42bc5560b047bdad458ac08c4f104f6d8a

2022-03-25 06:50 UTC, grigasp commented on docs/presentation/hierarchies/RelatedInstanceNodes.md
> +| **Performance note** | Setting the attribute to `Always` or `Never` may substantially improve performance of creating nodes in cases when  getting child nodes is expensive |
Made some changes, please check https://github.com/iTwin/itwinjs-core/pull/3388/commits/4f258d42bc5560b047bdad458ac08c4f104f6d8a

2022-03-25 08:25 UTC, roluk commented on docs/presentation/hierarchies/CustomNode.md
> +| **Performance note** | Setting the attribute to `Always` or `Never` may substantially improve performance of creating nodes in cases when  getting child nodes is expensive |
Looks much better now, thanks.

2022-03-25 08:32 UTC, roluk commented
You can mark this PR ready now.

> One thing I'm not sure about is whether we need to link each attribute to its markdown docs. At the moment I only link interfaces. Would be happy to hear your thoughts on this.

By now, documentation of specification attributes have so much information, that they each deserve separate documentation pages, just like TypeScript class members. Until this split is made, I would not bother linking each member to their respective documentation page.

2022-03-25 09:32 UTC, roluk approved these changes

2022-03-25 10:45 UTC, merged