Partial backport of texture size limit from Fix large textures #2244
iTwin/itwinjs-core pull request #3496
Opened 2022-04-07 20:44 UTC by DStradley

https://github.com/iTwin/itwinjs-core/pull/2244

2022-04-07 20:49 UTC, markschlosseratbentley requested changes
@markschlosseratbentley will test on iOS to verify fix.

2022-04-08 12:23 UTC, markschlosseratbentley commented
Some image differences detect - largely in the "large texture" datasets (pretty much expected).  Will wait for David to weigh in.

2022-04-08 16:11 UTC, DStradley commented
Yes, all the major diffs from 2.19.x are expected scaling artifacts on very large textures.  Looks good to me.

2022-04-08 16:53 UTC, markschlosseratbentley approved these changes

2022-04-08 16:54 UTC, markschlosseratbentley approved these changes

2022-04-08 17:40 UTC, merged