Presentation: filter button
iTwin/itwinjs-core pull request #3852
Opened 2022-06-23 06:39 UTC by MartynasStrazdas

Closes https://github.com/iTwin/itwinjs-backlog/issues/109
Renders action button on nodes for filtering.

2022-06-23 06:58 UTC, saskliutas requested changes

2022-06-23 06:58 UTC, saskliutas commented on common/api/components-react.api.md
> +    children?: React.ReactNode;
Don't see your changes in `components-react` package

2022-06-23 06:58 UTC, saskliutas commented on common/api/presentation-components.api.md
> +    onFilter?: (node: TreeModelNode) => void;
Maybe pass `TreeNodeItem` instead of `TreeModelNode` to be consistent with `TreeEvents`

2022-06-23 06:58 UTC, saskliutas commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
> +      onClick={() => props.onFilter}>
This should not work. `onFilter` is never invoked

2022-06-23 06:58 UTC, saskliutas commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
> +    <FilterButton
It looks like there is no need for separate `FilterButton` component as all it does just renders button

2022-06-23 06:58 UTC, saskliutas commented on presentation/components/src/test/tree/controlled/PresentationTreeNodeRenderer.test.tsx
> +        onFilter={buttonSpy(parentNode)}
You should not invoke the spy yourself.

2022-06-23 06:58 UTC, saskliutas commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
> +  const className = classnames("presentation-node", restProps.className);
`className` can be destructured from `props` on the line above

2022-06-23 06:58 UTC, saskliutas commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
> +      <SvgFilter className="presentation-filter-icon"/>
Does not look like `presentation-filter-icon` class provide any styling. Remove it?

2022-06-23 08:43 UTC, saskliutas requested changes

2022-06-23 08:43 UTC, saskliutas commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
> +    <IconButton className="presentation-filter-action-button" styleType="borderless" onClick={() => onFilter?.(restProps.node.item)}>
I think there is no need to render button if `onFilter` callback is not provided.

2022-06-23 09:02 UTC, saskliutas commented
One thing I noticed is that when filter button is clicked node is selected. I think this should not happens and it should be possible to click filter button without changing selection.

2022-06-23 10:58 UTC, saskliutas requested changes

2022-06-23 10:58 UTC, saskliutas commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
> +        onFilter?.(restProps.node.item);
No need to use optional chaining operator `?.` if you are rendering button only when `onFilter` is defined

2022-06-23 10:58 UTC, saskliutas commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.tsx
> +      <SvgFilter /></IconButton>}
Can you move `</IconButton> to separate line?

2022-06-23 13:17 UTC, saskliutas requested changes

2022-06-27 11:40 UTC, MartynasStrazdas commented
Which is better?
With medium spacing.
![image](https://user-images.githubusercontent.com/43886789/175932905-2e048dea-1720-442d-9024-b53ca4916286.png)
![image](https://user-images.githubusercontent.com/43886789/175932918-2212a518-2233-46a7-acd4-3d0f0ffcd4de.png)
With no spacing.
![image](https://user-images.githubusercontent.com/43886789/175933063-9b5baf4a-f527-443d-8606-ee1efca303ac.png)
![image](https://user-images.githubusercontent.com/43886789/175933099-967ff544-8ae6-4977-8081-dad7a1f24a62.png)

2022-06-28 06:23 UTC, grigasp commented
> Which is better? 

I vote for no spacing

2022-06-28 17:34 UTC, saskliutas requested changes

2022-06-29 08:14 UTC, saskliutas approved these changes

2022-06-29 08:35 UTC, roluk requested changes

2022-06-29 08:35 UTC, roluk commented on presentation/components/src/presentation-components/tree/controlled/PresentationTreeNodeRenderer.scss
>        display: flex;
`display: flex` should be on `.presentation-components-filter-action-button` div instead.

2022-06-29 09:00 UTC, roluk approved these changes

2022-06-29 10:10 UTC, GerardasB approved these changes

2022-06-29 15:00 UTC, merged