Presentation: instance filter dialog
iTwin/itwinjs-core pull request #4837
Opened 2022-12-21 12:09 UTC by MartynasStrazdas

2022-12-21 14:06 UTC, saskliutas requested changes
Don't forget `extract-api` and `change`

2022-12-21 14:06 UTC, saskliutas commented on presentation/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx
> +    expect(applyButton).to.not.be.null;
This looke like unnecessary. Check below will faile if this is `null`. Same in other test

2022-12-21 14:06 UTC, saskliutas commented on presentation/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx
> +    if (applyButton)
Unnecessary if. Same in other test

2022-12-21 14:06 UTC, saskliutas commented on presentation/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx
> +    },
```suggestion
    filter: {
      field: propertiesField,
      operator: PropertyFilterRuleOperator.IsNull,
      value: undefined,
    },
```

2022-12-21 14:06 UTC, saskliutas commented on presentation/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx
> +    expect(actualTitle).to.not.be.null;
```suggestion
    expect(queryByText(title)).to.not.be.null;
```

2022-12-21 14:06 UTC, saskliutas commented on presentation/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx
> +    expect(actualTitle).to.not.be.null;
```suggestion
    expect(queryByText(count)).to.not.be.null;
```

2022-12-22 11:37 UTC, saskliutas requested changes

2022-12-22 11:37 UTC, saskliutas commented on presentation/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.tsx
> +interface PresentationInstanceFilterDialogProps extends Omit<PresentationInstanceFilterBuilderProps, "onInstanceFilterChanged"> {
Should be exported.

2022-12-22 11:37 UTC, saskliutas commented on presentation/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.scss
> +
Remove empty line

2022-12-29 07:33 UTC, saskliutas commented on presentation/components/src/test/instance-filter-builder/PresentationInstanceFilterDialog.test.tsx
> +
Looks like there are some unnecessary empty lines left in this file. Please remove them

2022-12-29 07:35 UTC, saskliutas commented on presentation/components/src/presentation-components/instance-filter-builder/PresentationInstanceFilterDialog.tsx
> +  return <Dialog isOpen={isOpen}
There are still some fomatting issues left

2022-12-29 12:02 UTC, pmconne approved these changes

2022-12-30 19:20 UTC, NancyMcCallB approved these changes

2023-01-02 14:15 UTC, saskliutas approved these changes

2023-01-03 14:38 UTC, saskliutas commented
@MarcBedard8 @mdastous-bentley can you take a look at changes in `map-layers`?

2023-01-05 15:51 UTC, mdastous-bentley approved these changes

2023-01-06 07:14 UTC, merged