Presentation: Add an option to apply content modifiers to nested content
iTwin/itwinjs-core pull request #5293
Opened 2023-03-27 16:36 UTC by medikornov

2023-03-28 06:06 UTC, grigasp requested changes
TODOs:
- [ ] Add to `/docs/presentation/content/ContentModifier.md`.
- [ ] Add a section to `NextVersion.md`
- [ ] Update our supplemental rulesets at `/presentation/backend/assets/supplemental-presentation-rules` to make use of this new attribute.

2023-03-28 06:06 UTC, grigasp commented on presentation/common/src/presentation-common/rules/content/modifiers/ContentModifier.ts
> +   * [relatedProperties]($docs/presentation/content/RelatedPropertiesSpecification.md) specifications should also be applied on
```suggestion
   * Specifies whether [`calculatedProperties`]($docs/presentation/content/CalculatedPropertiesSpecification.md) and
   * [`relatedProperties`]($docs/presentation/content/RelatedPropertiesSpecification.md) specifications should also be applied on
```

2023-03-28 06:06 UTC, grigasp commented on full-stack-tests/presentation/src/learning-snippets/content/rules/ContentModifier.test.ts
> +            // apply related and calculated properties on nested properties
```suggestion
            // add a content modifier for `SpatialViewDefinition` elements
```

2023-03-28 06:06 UTC, grigasp commented on full-stack-tests/presentation/src/learning-snippets/content/rules/ContentModifier.test.ts
> +            applyOnNestedContent: true,
```suggestion
            // set `applyOnNestedContent: true` to get this modifier applied when `SpatialViewDefinition` content is loaded indirectly
            applyOnNestedContent: true,
```

2023-04-05 09:02 UTC, medikornov commented on full-stack-tests/presentation/src/learning-snippets/content/rules/ContentModifier.test.ts
> +                  targetClass: { schemaName: "BisCore", className: "SpatialViewDefinition" },
fixed

2023-04-05 09:03 UTC, medikornov commented on full-stack-tests/presentation/src/learning-snippets/content/rules/ContentModifier.test.ts
> +        expect(spatialViewDefinitionProperties[getFieldByLabel(content!.descriptor.fields, "Calculated for SpatialViewDefinition").name]).to.eq("5.9371887957409877,3.2424499696297646,40");
fixed?

2023-04-05 09:04 UTC, medikornov commented on presentation/common/src/presentation-common/rules/content/modifiers/ContentModifier.ts
> +   * [relatedProperties]($docs/presentation/content/RelatedPropertiesSpecification.md) specifications should also be applied on
fixed

2023-04-05 09:04 UTC, medikornov commented on full-stack-tests/presentation/src/learning-snippets/content/rules/ContentModifier.test.ts
> +            // apply related and calculated properties on nested properties
fixed

2023-04-05 09:04 UTC, medikornov commented on full-stack-tests/presentation/src/learning-snippets/content/rules/ContentModifier.test.ts
> +            applyOnNestedContent: true,
fixed

2023-04-05 12:15 UTC, grigasp commented on docs/changehistory/NextVersion.md
> +Previously, the calculated and related properties defined in the content modifier were only applied to displayed instances, but not to related instances. In most cases, when showing related instance
```suggestion
Previously, the [calculated](../presentation/content/ContentModifier.md#attribute-calculatedproperties) and [related properties](../presentation/content/ContentModifier.md#attribute-relatedproperties) defined in [content modifiers](../presentation/content/ContentModifier.md) were only applied on directly loaded instances' content. Occasionally, there is a need to request calculated and/or related properties to be loaded for specific instances in all situations, no matter if their content is loaded directly or indirectly. Previously that was only possible by chaining [related properties](../presentation/content/ContentModifier.md#attribute-relatedproperties) and [nested related properties](../presentation/content/RelatedPropertiesSpecification.md#attribute-nestedrelatedproperties) attributes. Now the content modifier rule has an attribute [`applyOnNestedContent`](../presentation/content/ContentModifier.md#attribute-applyonnestedcontent) which indicates if the modifier should be used on nested content. This removes the need to have duplicate [related properties specifications](../presentation/content/RelatedPropertiesSpecification.md) in those situations.
```

2023-04-05 12:28 UTC, medikornov commented on presentation/common/src/presentation-common/rules/content/modifiers/ContentModifier.ts
> +  applyOnNestedContent?: boolean;
fixed

2023-04-05 12:39 UTC, grigasp approved these changes
Need `extract-api` and `rush change`, but otherwise looks good

2023-04-06 09:49 UTC, grigasp commented
/azp run

2023-04-06 13:24 UTC, merged