Presentation: Values formatting on frontend
iTwin/itwinjs-core pull request #5303
Opened 2023-03-28 11:41 UTC by saskliutas

Added `ContentPropertyValuesFormatter` for getting display values for different type raw values in content. This is necessary for supporting Content formatting on the frontend.
Added ability to request Content without formatted values and format them on the frontend. 

imodel-native: https://github.com/iTwin/imodel-native/tree/presentation/values_formatting_rework
Native changes:

Part of https://github.com/iTwin/itwinjs-core/issues/5029

2023-03-28 11:56 UTC, pmconne approved these changes

2023-03-28 14:43 UTC, grigasp requested changes

2023-03-28 14:43 UTC, grigasp commented on presentation/backend/src/presentation-backend/PresentationManager.ts
> +      ...requestOptions,
there seems to be a problem when `requestOptions.omitFormattedValues === false && this.props.schemaContextProvider !== undefined`

2023-03-29 11:13 UTC, saskliutas commented on presentation/common/src/test/content/PropertyFormatter.test.ts
> +  it("creates formatter", async () => {
Removed this function and test

2023-03-29 11:46 UTC, grigasp approved these changes

2023-03-29 14:18 UTC, merged