rm deprecated 2.x ChangeSummaryManager api
iTwin/itwinjs-core pull request #5387
Opened 2023-04-12 23:14 UTC by aruniverse

2023-05-09 19:52 UTC, aruniverse commented
@diegopinate mind reviewing the changes to the ChangesetManager (in case it affects you with VC)

2023-05-10 13:15 UTC, diegopinate commented
@aruniverse, it shouldn't impact it. We use the change summary API that's in the addon internally, and you didn't make any changes to the ChangedElementsManager, so this should be fine.

2023-05-10 13:24 UTC, saskliutas requested changes

2023-05-10 13:24 UTC, saskliutas commented on presentation/common/src/presentation-common/RulesetsFactory.ts
> +    { schemaName, classNames: [className] };
```suggestion
  return { schemaName, classNames: [className], arePolymorphic: true }
```

2023-05-10 13:24 UTC, saskliutas commented on presentation/common/src/presentation-common/EC.ts
> +  arePolymorphic?: boolean;
Please remove new `arePolymorphic` property from `ClassInfo` types.

2023-05-10 14:22 UTC, Jake-Screen commented on presentation/common/src/presentation-common/RulesetsFactory.ts
> +    { schemaName, classNames: [className] };
change made

2023-05-10 14:25 UTC, pmconne commented on docs/changehistory/NextVersion.md
> +### Removed deprecated items
We already have a "Deprecated API removals" section under "Breaking changes".
Spelling: "polymorphicly" => "polymorphically".

2023-05-10 14:48 UTC, saskliutas approved these changes

2023-05-10 15:28 UTC, aruniverse commented on docs/changehistory/NextVersion.md
> +The deprecated field `handleInstancesPolymorphically?` of [ContentInstancesOfSpecificClassesSpecification]($presentation-common) has been removed. To specify handling polymorphically, specify the val
```suggestion
The deprecated field `handleInstancesPolymorphically` of [ContentInstancesOfSpecificClassesSpecification]($presentation-common) has been removed. To specify handling polymorphically, specify the value in `classes.arePolymorphic` or `excludedClasses.arePolymorphic`.
```

2023-05-10 15:49 UTC, merged