PolyfaceQuery.sweepLineStringToFacets: enhancement to (now-deprecated) PolyfaceQuery.sweepLinestringToFacetsXYReturnLines
iTwin/itwinjs-core pull request #5684
Opened 2023-06-23 22:18 UTC by EarlinLutz

This is an enhancement to behavior of PolyfaceQuery.sweepLinestringToFacetsXYReturnChain.  It provides
  * control over
* https://github.com/iTwin/itwinjs-core/issues/5507 observes unexpected linework returned from PolyfaceQuery.sweepLinestringToFacetsXYReturnChain.
* for the test case given, the output described as zingers is correct.
  * these lines are draped onto facets that are almost but not quite vertical.  The result is correct
  * a second mesh that shares an edge with the almost-vertical

2023-06-26 19:28 UTC, pmconne requested changes

2023-06-26 19:28 UTC, pmconne commented on docs/changehistory/NextVersion.md
> +### Draping (sweeping) a linestring onto a mesh
```suggestion
### Sweeping a linestring to facets
```

2023-06-26 19:28 UTC, pmconne commented on docs/changehistory/NextVersion.md
> +  - [Sweeping a linestring to facets]
```suggestion
  - [Sweeping a section to a sequence of planes](#sweeping-a-section-to-a-sequence-of-planes)
  - [Sweeping a linestring to facets](#sweeping-a-linestring-to-facets)
```

2023-06-26 19:28 UTC, pmconne commented on docs/changehistory/NextVersion.md
> +  - [Sweeping a linestring to facets]
These are supposed to be links. The first one was a link prior to your edit.

2023-06-26 19:29 UTC, pmconne commented on docs/changehistory/NextVersion.md
> +  - [Sweeping a linestring to facets]
Unless you object to proposed changes, you can just use the "Commit suggestion" buttons to apply them.

2023-06-26 19:31 UTC, pmconne commented on core/geometry/src/geometry3d/Angle.ts
> +   * Return a (new) Angle object with the default "small" angle measurement (Geometry.smallAngleRadians)
```suggestion
   * Return a new `Angle` object with the default "small" angle measurement specified by [[Geometry.smallAngleRadians]].
```

2023-06-26 19:31 UTC, pmconne commented on core/geometry/src/geometry3d/Angle.ts
> + * Test if this angle has magnitude less than other.
```suggestion
 * Test if this angle has magnitude no greater than that of `other`.
```

2023-06-26 19:32 UTC, pmconne commented on core/geometry/src/polyface/PolyfaceQuery.ts
> +    * @deprecated in 4.x. Use [PolyfaceQuery.sweepLineStringToFacets] to get further options.
```suggestion
    * @deprecated in 4.x. Use [[PolyfaceQuery.sweepLineStringToFacets]] to get further options.
```

2023-06-26 19:33 UTC, pmconne commented on core/geometry/src/polyface/PolyfaceQuery.ts
> +   * * this calls  [PolyfaceQuery.sweepLineStringToFacets] with options created by
```suggestion
   * * this calls  [[PolyfaceQuery.sweepLineStringToFacets]] with options created by
```

`[[ApiName]]` to link to an API in the same package.
`[ApiName]($package-alias)` to link to an API in a different package.

2023-06-26 19:54 UTC, pmconne approved these changes

2023-06-28 22:45 UTC, dassaf4 requested changes
Looks great! I pushed some doc changes and cleaned up some stuff. Please review.

2023-06-29 13:19 UTC, dassaf4 approved these changes

2023-06-29 22:26 UTC, merged