Model Display Transform Provider provides 'base transform'
iTwin/itwinjs-core pull request #5917
Opened 2023-08-28 17:08 UTC by Ellord207

2023-08-29 17:34 UTC, anmolshres98 commented on core/frontend/src/ViewState.ts
> +   * let transform = baseTranfrom.inverse()!.multiplyTransformTransform(modelTransform);
Two instance: line 71 and 72 should be `baseTransform` instead of `baseTranfrom` I believe

2023-08-29 20:19 UTC, anmolshres98 requested changes

2023-08-29 20:19 UTC, anmolshres98 commented on core/frontend/src/ViewState.ts
> +   * let transform = baseTranform.inverse()!.multiplyTransformTransform(modelTransform);
Now it is `baseTranForm` :)
```suggestion
   * let transform = baseTransform.inverse()!.multiplyTransformTransform(modelTransform);
```

2023-08-29 20:19 UTC, anmolshres98 commented on core/frontend/src/ViewState.ts
> +   * transform = transform.multiplyTransformTransform(baseTranform);
```suggestion
   * transform = transform.multiplyTransformTransform(baseTransform);
```

2023-08-29 20:40 UTC, pmconne requested changes
I will review in a bit.

2023-09-05 19:54 UTC, markschlosseratbentley approved these changes

2023-09-07 14:01 UTC, aruniverse commented
@pmconne mind reviewing?

2023-09-07 14:04 UTC, pmconne commented
> @pmconne mind reviewing?

Where are tests?

2023-09-07 14:33 UTC, pmconne commented
I'll finish this up.

2023-09-08 12:26 UTC, pmconne commented
Superseded by #5956. Thanks @Ellord207.

2023-09-08 12:26 UTC, closed without merging