Edl/mesh vertex loops
iTwin/itwinjs-core pull request #5963
Opened 2023-09-08 19:39 UTC by dassaf4

- Conventional polyface data defines each facet by a sequence of indices of point coordinates "around the facet"
- These indices do not indicate what facet is adjacent "across each edge of the facet"
- new method [IndexedPolyface.buildEdgeMateIndices] constructs indices for the cross-edge relationship.
- Following that construction, the following queries support navigation around each facet, around each vertex, and across each edge:
  - polyface.readIndexToEdgeMate = (possibly undefined) readIndex of the edge mate.
  - polyface.readIndexToSuccessorAroundFacet = readIndex of the next vertex around the facet.
  - polyface.readIndexToPredecessorAroundFacet = readIndex of the previous vertex around the facet
  - polyface.readIndexToSuccessorAroundVertex = (possibly undefined) readIndex of the next vertex around the facet.
  - polyface.readIndexToPredecessorAroundVertex = (possibly undefined) readIndex of the previous vertex around the facet

2025-01-17 20:42 UTC, saeeedtorabi requested changes

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedEdgeMatcher.ts
> + *   * [2] is "facet index".
not sure if quote mark is needed OR you should add quote for [0] and [1] as well

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> +
I though navigation around facets, across edges, and around vertices are already available.

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> + *   * This array essentially completes the topology of the `IndexedPolyface` by storing facet adjacency.
what do you mean by "completes"? Was the topoly "incomplete" before this PR?

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> + * * When facets are viewed so that the face loops stored in the [[PolyfaceData]] `pointIndex` array have
I move the image (line 59-70) to line 32

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> + *   * Invalid walkers can also occur while traversing a non-manifold mesh. Such meshes feature edge(s) with more than
what is a "non-manifold mesh"? Is it documented somewhere in our code or docs?

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> +  public get edgeIndex(): number | undefined { return this._edgeIndex; }
I think we agreed that "return" should be on a new line. Same for next getters. Note that I am fixing this in BSpline classes.

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/Polyface.ts
> +   * Given an array of strictly increasing numbers, find the index of the largest number that is less than or equal
```suggestion
   * Given an array of monotone numbers (i.e., strictly increasing numbers), find the index of the largest number that is less than or equal
```

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/Polyface.ts
> +   * * For regularly spaced numbers (e.g. data is the _facetStart indices for a triangulated mesh) the proportional
```suggestion
   * * For regularly spaced numbers (e.g., data is the _facetStart indices for a triangulated mesh) the proportional
```

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/polyface/Polyface.ts
> +  public facetIndex0(facetIndex: number): number { return this._facetStart[facetIndex]; }
For consistenct please move returns to a new line

2025-01-17 20:42 UTC, saeeedtorabi commented on core/geometry/src/test/polyface/IndexedPolyfaceWalker.test.ts
> +    //    5   2   4
Is this the polyface visual? It's not clear to me. It would be great if you can visulize the polyface same as you did in `IndexedPolyfaceWalker.ts`
```
  # --------- # --------- #
  |   < < < B | F         |
  |         ^ | v         |
  |         ^ | v         |
  |         ^ | v         |
  | C > > > A | D > > >   |
  # --------- # --------- #
  |   < < < E |           |
  |           |           |
  |           |           |
  |           |           |
  # --------- # --------- #
  ```

2025-01-17 21:34 UTC, dassaf4 commented on core/geometry/src/polyface/IndexedEdgeMatcher.ts
> + *   * [2] is "facet index".
To be addressed in next commit.

2025-01-17 21:35 UTC, dassaf4 commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> +
Before this PR, `PolyfaceData` only stored enough data to walk around a facet: the face loop of each facet is stored in the `pointIndex` array.

2025-01-17 21:35 UTC, dassaf4 commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> + *   * This array essentially completes the topology of the `IndexedPolyface` by storing facet adjacency.
Yes, it was incomplete. `PolyfaceData` did not store facet adjacency.

2025-01-17 21:35 UTC, dassaf4 commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> + * * When facets are viewed so that the face loops stored in the [[PolyfaceData]] `pointIndex` array have
To be addressed in next commit.

2025-01-17 21:35 UTC, dassaf4 commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> + *   * Invalid walkers can also occur while traversing a non-manifold mesh. Such meshes feature edge(s) with more than
This is a familiar concept in solid modeling. It's defined in the next line. Formally, a 2-manifold is topologically equivalent to a plane in an open neighborhood of each of its interior points. We usually simplify this to just "manifold" when talking about surfaces.

2025-01-17 21:36 UTC, dassaf4 commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> +  public get edgeIndex(): number | undefined { return this._edgeIndex; }
Yes, this typically allows native breakpoints to be set in Visual Studio. I don't think it's necessary for setting TypeScript breakpoints in Code, but it can't hurt. To be addressed in next commit.

2025-01-17 21:36 UTC, dassaf4 commented on core/geometry/src/polyface/Polyface.ts
> +   * Given an array of strictly increasing numbers, find the index of the largest number that is less than or equal
Hmm, monotone means increasing or decreasing. I'll rename in next commit.

2025-01-17 21:36 UTC, dassaf4 commented on core/geometry/src/polyface/Polyface.ts
> +   * * For regularly spaced numbers (e.g. data is the _facetStart indices for a triangulated mesh) the proportional
To be addressed in next commit.

2025-01-17 21:37 UTC, dassaf4 commented on core/geometry/src/polyface/Polyface.ts
> +  public facetIndex0(facetIndex: number): number { return this._facetStart[facetIndex]; }
To be addressed in next commit.

2025-01-17 21:37 UTC, dassaf4 commented on core/geometry/src/test/polyface/IndexedPolyfaceWalker.test.ts
> +    //    5   2   4
Yes, it's visual. But not the same. These are vertex indices, not edge indices. ASCII graphics would be overkill. To be addressed in next commit.

2025-01-21 16:15 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> + *   * Invalid walkers can also occur while traversing a non-manifold mesh. Such meshes feature edge(s) with more than
ok I see. so non-maniold can have more than two adjacent facets meaning it's not like a surface and is more a complicared mesh.

2025-01-21 16:16 UTC, saeeedtorabi commented on core/geometry/src/polyface/IndexedPolyfaceWalker.ts
> +  public get edgeIndex(): number | undefined { return this._edgeIndex; }
yes and it's better to keep consistency.

2025-01-21 16:19 UTC, saeeedtorabi approved these changes

2025-01-21 18:11 UTC, aruniverse approved these changes

2025-01-21 23:55 UTC, merged