rm require in core-frontend
iTwin/itwinjs-core pull request #6025
Opened 2023-09-22 17:06 UTC by aruniverse

2023-09-22 17:07 UTC, aruniverse commented on core/frontend/src/IModelApp.ts
> +// @ts-expect-error resolves from the lib/{cjs,esm} dir
does correctly resolve the pkg.json at runtime and will not copy the package.json into the lib/esm or lib/cjs dir at compile time

2023-09-25 18:31 UTC, pmconne commented
@markschlosseratbentley @iTwin/itwinjs-core-display does anyone have some time to verify DTA and DPTA still work?

2023-09-25 18:42 UTC, markschlosseratbentley commented
> @markschlosseratbentley @iTwin/itwinjs-core-display does anyone have some time to verify DTA and DPTA still work?

I will verify DTA in a bit.
I propose we kick off an Image Tests on this branch to verify DPTA.

Unless that conflicts with @MarcNeely using the Image Tests system today.

2023-09-25 18:55 UTC, markschlosseratbentley requested changes
I will approve once we verify DTA and DPTA.

2023-09-25 19:10 UTC, markschlosseratbentley commented
DTA still appears to build + run + rebuild + detect code changes.  Using `npm run start:electron` still only shows .js files, but I think that was a previous problem (`npm run start` shows TypeScript).

2023-09-25 21:04 UTC, markschlosseratbentley approved these changes
Image Tests successfully ran with a version of DPTA built off this branch.

2023-09-25 21:06 UTC, merged