Addded support for CurveChainWithDistanceIndex in CurveCurveCloseApproachXY
iTwin/itwinjs-core pull request #6052
Opened 2023-09-29 21:14 UTC by saeeedtorabi

- Now CurveCurveCloseApproachXY supports CurveChainWithDistanceIndex with correct fractions.
- Added tests for CurveChainWithDistanceIndex with line segment, line string, arc, and another CurveChainWithDistanceIndex.

Also:
- Improved docs and code.
- Fixed formatting issues.
- Added math details.

2023-10-02 21:12 UTC, dassaf4 requested changes
Looks good! `CurveChainWithDistanceIndex` is really powerful, as it enables the imposition of an ideal global parameterization (fractional arclength) on any `CurveChain`.  This PR goes a long way toward laying the foundation for, and providing the first example of, its participation in internal curve contexts.

I recommended some changes to comment blocks for this review; but I pushed more substantive changes directly onto the branch. Please review. Mainly these changes:
* handle `Loop`-based `CurveChainWithDistanceIndex` objects,
* obviate the need for existing subclasses of `GeometryHandler` to react to this PR, and
* streamline a few classes/methods

2023-10-03 17:29 UTC, saeeedtorabi commented on core/geometry/src/curve/CurveChainWithDistanceIndex.ts
> +    result.direction.scaleInPlace(a); // scale direction by L/||C'||
yes but they make the code easier to understand and connect to the doc. I prefer to keep them as they are!

2023-10-03 18:03 UTC, dassaf4 approved these changes

2023-10-03 18:05 UTC, bbastings approved these changes

2023-10-03 18:23 UTC, merged