Add AuthorizationClient onAccessTokenChanged event
iTwin/itwinjs-core pull request #6122
Opened 2023-10-19 18:43 UTC by ben-polinsky

Add an optional `onAccessTokenChanged` `BeEvent` to the `AuthorizationClient` interface.
We plan to make this property required in 5.0.

2023-10-19 18:51 UTC, aruniverse approved these changes

2023-10-19 18:59 UTC, MichaelBelousov approved these changes

2023-10-20 06:37 UTC, ImVeryLost approved these changes

2023-11-10 23:17 UTC, calebmshafer commented
@ben-polinsky @aruniverse what is the implementation of this going to look like in the Desktop and Mobile auth? I'm still not clear of the requirement for this.

I'm assuming the reason you would need to get an event is if you're caching the token somewhere and need to make sure it's still valid, plus avoid the overhead of calling the getAccessToken() method all the time. Is that the reasoning here?

This interface, and iModelApp, assume that the implementations passed in have done the most optimal thing on their side and keep the token up-to-date.

There is special cache handling in both the mobile and desktop clients so their specific implementations kept the correct token sync-ed between the backend and frontend processes.

2023-12-13 20:51 UTC, aruniverse commented
> what is the implementation of this going to look like in the Desktop and Mobile auth

Desktop already implements this, [see](https://github.com/iTwin/auth-clients/blob/main/packages/electron/src/renderer/Client.ts#L85)

Mobile, im not sure. Maybe @tcobbs-bentley can chime in there

2023-12-13 20:56 UTC, calebmshafer requested changes
Going to block this change for now. Let's have a design discussion around this more and look at all 3 implementations (web, mobile, desktop) before moving forward with it.

2023-12-13 20:57 UTC, tcobbs-bentley commented
> > what is the implementation of this going to look like in the Desktop and Mobile auth
> 
> Desktop already implements this, [see](https://github.com/iTwin/auth-clients/blob/main/packages/electron/src/renderer/Client.ts#L85)
> 
> Mobile, im not sure. Maybe @tcobbs-bentley can chime in there

MobileHost already has onAuthAccessTokenChanged that gets posted when the native side auth client indicates the change, so moving this to the AuthorizationClient is probably fine (although I'm not sure about the implementation details of the move).

2024-03-02 02:00 UTC, toddsouthenbentley commented
This PR would be very for my work with iTwin Studio.

In an effort to get it rolling, I created a draft PR of the changes required for Mobile: #6485

2025-03-14 16:47 UTC, closed without merging