Change gpuMemoryLimit setting used when undefined
iTwin/itwinjs-core pull request #6463
Opened 2024-02-23 20:53 UTC by DStradley

For non-mobile devices, the gpuMemoryLimit used a setting of "none" (no limit) when it was not defined.  This changes that setting to TileAdmin.nonMobileUndefinedGpuMemoryLimit (6,000 MB) instead.

Some very large reality data sets and imodels could on occasion cause a WebGL context loss with no limit imposed, so this attempts to set a generous limit that should prevent most of these problems for the common case of the gpuMemoryLimit being undefined.  If desired, the limit can still be set to "none".

See https://github.com/iTwin/itwinjs-backlog/issues/1047

2024-02-23 21:14 UTC, pmconne requested changes
Documentation on line 95 is now a lie.
`  /** Limits applied to clients running on non-mobile devices. Defaults to "none" if undefined. */`

2024-02-23 21:15 UTC, pmconne commented on core/frontend/src/tile/TileAdmin.ts
> +  export const nonMobileUndefinedGpuMemoryLimit = 6000 * 1024 * 1024; // 6,000 MB - used when nonMobile limit is undefined
This is implicitly `@public`. If you didn't intend that, add `@internal`. If you did intend that, give it a better name and document it.

2024-02-23 21:42 UTC, pmconne commented on core/frontend/src/tile/TileAdmin.ts
> +  export const nonMobileUndefinedGpuMemoryLimit = 6000 * 1024 * 1024; // 6,000 MB - used when nonMobile limit is undefined
Fixed to use `/** doc comment */`.
You'll need to `npm run build` core-frontend and then `npm run extract-api`.

2024-02-23 21:46 UTC, pmconne approved these changes

2024-02-23 21:52 UTC, ben-polinsky approved these changes

2024-02-23 22:14 UTC, merged

2024-02-26 19:21 UTC, markschlosseratbentley commented
@aruniverse can we backport this to 4.4?
cc @danieliborra

2024-02-26 19:22 UTC, aruniverse commented
@mergifyio backport release/4.4.x