Prohibit `Object` methods being called through IPC
iTwin/itwinjs-core pull request #6780
Opened 2024-05-31 14:16 UTC by GytisCepk

This prevent methods inherited from `Object` class (e.g.: `toString`, `__defineSetter__`) from being called through IPC. 

It would be great to also prohibit `private` methods in custom IPC handlers from being callable, but it's not possible, since, if they are defined `private` in TypeScript, this information is lost during runtime. Added a recommendation to the documentation to either remove private methods from IPC handlers or define them as [JavaScript private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties).

2024-06-03 08:56 UTC, GytisCepk commented
> Your PR description should specify why you want to do this.

Updated description.

2024-06-03 12:22 UTC, aruniverse approved these changes

2024-06-03 12:22 UTC, pmconne requested changes
I want to discuss with @wgoehrig first.

2024-10-22 09:12 UTC, pmconne approved these changes

2024-10-22 10:44 UTC, merged